name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Build & Push
    runs-on: ubuntu

    env:
      NAME: filmhaven
      PLATFORMS: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          cache-image: false

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Get Version
        uses: saionaro/extract-package-version@v1.3.0
        id: version

      - name: Login to Local Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.EXTERNAL_SERVER_DOMAIN }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.AUTH }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.GH_AUTH }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          registry: docker.io
          username: ${{ vars.DH_USERNAME }}
          password: ${{ secrets.DH_AUTH }}

      - name: Build & Push to Registries
        uses: docker/build-push-action@v6.18.0
        with:
          tags: |
            ${{ env.EXTERNAL_SERVER_DOMAIN }}/${{ vars.USERNAME }}/${{ env.NAME }}:latest
            ghcr.io/${{ vars.GH_USERNAME }}/${{ env.NAME }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ vars.GH_USERNAME }}/${{ env.NAME }}:latest
            docker.io/${{ vars.DH_USERNAME }}/${{ env.NAME }}:${{ steps.version.outputs.version }}
            docker.io/${{ vars.DH_USERNAME }}/${{ env.NAME }}:latest
          platforms: ${{ env.PLATFORMS }}
          push: true
          context: .
